
spring:
  #Rabbit MQ configurations  
   rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
  #MySQL DB configurations
   datasource:
      url: jdbc:mysql://localhost:3306/department_microservice_db
      username: root
      password: "#m@y25nov1998#"
      driver-class-name: com.mysql.cj.jdbc.Driver
   jpa:
      database-platform: org.hibernate.dialect.MySQL5Dialect
      hibernate:
         ddl-auto: update
  #Reddis Session management configurations
   redis:
      host: localhost
      port: 6379
   session:
      store-type: redis

queue:
   name: test   

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost