server:
   port : 9094
#    ssl:
#      key-store-type: PKCS12
#      key-store: 'src/main/resources/keystore/springbootssl.p12'
#      key-store-password: changeit
#      key-alias: springbootssl

spring:
   profiles:
      active: TEST
   application:
      name: USER-SERVICE
logging:
   level:
      org:
         springframework:
            web: DEBUG
   file: 'src/main/resources/logs/spring-boot-logging.log'
---
spring:
   config:
      activate:
         on-profile: TEST
      import: "optional:configserver:"
   cloud:
      config:
         uri: http://localhost:8888
---
spring:
   config:
      activate:
         on-profile: DEV
      import: "optional:configserver:"
   cloud:
      config:
         uri: http://user-service-config-server-1:8888