
spring:
  #Rabbit MQ configurations  
   rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
  #MySQL DB configurations
   datasource:
      url: jdbc:mysql://mysql-container:3306/user_microservice_db
      username: root
      password: "#m@y25nov1998#"
      driver-class-name: com.mysql.cj.jdbc.Driver
   jpa:
      hibernate:
         ddl-auto: update
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQLDialect
  #Reddis Session management configurations
   redis:
      host: localhost
      port: 6379
   session:
      store-type: redis

queue:
   name: test   

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://spring-service-registry:8761/eureka/
  instance:
    hostname: localhost