version: '3'
services:
  mysqldb-container:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "#m@y25nov1998#"
      MYSQL_DATABASE: "user_microservice_db"
    ports:
      - "3306:3306"
    networks:
      - spring-microservices-network
  rabbitmq-container:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring-microservices-network
  redis-container:
    image: redis:7-alpine
    ports:
      - "6380:6380"
    networks:
      - spring-microservices-network
  prometheus-container:
    image: 'prom/prometheus:v2.14.0'
    ports:
      - '9090:9090'
    command: '--config.file=/etc/prometheus/config.yml'
    volumes:
      - './prometheus.yml:/etc/prometheus/config.yml'
    networks:
      - spring-microservices-network
  grafana-container:
    image: 'grafana/grafana:6.5.0'
    ports:
      - '3000:3000'
    networks:
      - spring-microservices-network
  service-registry:
    image: 'service-registry:1.0'
    ports:
      - '8761:8761'
    networks:
      - spring-microservices-network
  config-server:
    image: 'config-server:1.0'
    ports:
      - '8888:8888'
    networks:
      - spring-microservices-network
#  user-service:
#    depends_on:
#      - service-registry
#      - config-server
#      - mysqldb-container
#      - rabbitmq-container
#      - redis-container
#    image: 'user-service:1.0'
#    ports:
#      - '9092:9092'
#    networks:
#      - spring-microservices-network

networks:
  spring-microservices-network:
    driver: bridge