scrape_configs:
  - job_name: 'jobName'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service-user-service-1:9092']